name: Update Daily Results

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ===== BAGIAN TES DIAGNOSTIK DIMULAI DI SINI =====
      - name: Run diagnostic checks and script
        run: |
          echo "--- Memulai Tes Diagnostik ---"

          echo "1. Menampilkan daftar file di direktori:"
          ls -l

          echo "2. Mengecek versi Python:"
          python --version

          echo "3. Mengecek library yang terinstal:"
          pip list

          echo "4. Menjalankan skrip update_results.py:"
          python update_results.py

          echo "--- Tes Diagnostik Selesai ---"
      # ===== BAGIAN TES DIAGNOSTIK SELESAI =====

      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "BOT: Auto-update result files"
          branch: main
