name: Update Daily Results

on:
  schedule:
    - cron: '30 6 * * *'
    - cron: '15 11 * * *'
    - cron: '15 14 * * *'
    - cron: '15 16 * * *'
    - cron: '15 17 * * *'
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python update_results.py

      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "BOT: Auto-update result files"
          branch: main
