# Nama alur kerja yang akan muncul di tab Actions
name: Update Daily Results

# Pemicu (trigger) untuk menjalankan alur kerja
on:
  schedule:
    # Menjalankan setiap hari pada pukul 18:00 UTC.
    # Ini sekitar pukul 01:00 WIB (dini hari), waktu yang baik setelah semua hasil keluar.
    # Formatnya adalah: Menit Jam Hari(Bulan) Bulan Hari(Minggu)
    - cron: '0 18 * * *'
  workflow_dispatch:
    # Baris ini memungkinkan Anda menjalankan workflow secara manual dari tab Actions

# Daftar pekerjaan (jobs) yang akan dijalankan
jobs:
  update-files:
    # Menjalankan di lingkungan virtual Ubuntu terbaru
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dieksekusi
    steps:
      # Langkah 1: Mengunduh (checkout) kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Mengatur lingkungan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Anda bisa menggunakan versi Python lain jika perlu

      # Langkah 3: Menginstal library yang dibutuhkan oleh skrip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Langkah 4: Menjalankan skrip Python untuk memperbarui file
      - name: Run update script
        run: python update_results.py

      # Langkah 5: Melakukan commit dan push perubahan kembali ke repositori
      # Menggunakan Action yang sudah jadi untuk mempermudah
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Pesan commit yang akan digunakan
          commit_message: "BOT: Auto-update result files"
          # Branch tempat perubahan akan di-push
          branch: main
