name: Update Daily Results

on:
  schedule:
    # Jam 13:30 WIB: Untuk update Bullseye & Sydney
    - cron: '30 6 * * *'
    # Jam 18:15 WIB: Untuk update Singapore & Morocco 18
    - cron: '15 11 * * *'
    # Jam 21:15 WIB: Untuk update Morocco 21
    - cron: '15 14 * * *'
    # Jam 23:15 WIB: Untuk update Hongkong
    - cron: '15 16 * * *'
    # Jam 00:15 WIB: Untuk update Morocco 00 (tengah malam)
    - cron: '15 17 * * *'
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python update_results.py

      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "BOT: Auto-update result files"
          branch: main
