name: Update Daily Results

on:
  workflow_dispatch:
  schedule:
    # Jalankan setiap jam 11 malam WIB (16:00 UTC)
    - cron: '0 16 * * *'

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python update_results.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add keluaran*.txt
          # Commit hanya jika ada perubahan file
          if ! git diff --staged --quiet; then
            git commit -m "Update daily results"
            git push
          else
            echo "No changes to commit."
          fi

      # Langkah ini akan berjalan HANYA JIKA langkah di atasnya gagal
      - name: Upload Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            *.png
            *.html
